version: '3'
services:
  zb_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ${SSL_DIR}:/ssl
    networks:
     - zb_net

networks:
  zb_net:
    external: true
